#server:
#  port: 8082
#  servlet:
#    context-path: /vehicle-service
#
#spring:
#  application:
#    name: VEHICLE-SERVICE
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082

spring:
  application:
    name: vehicle-service
  config:
    import: "optional:configserver:http://localhost:8888"
