#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#        - id: vehicle-service
#          uri: lb://VEHICLE-SERVICE
#          predicates:
#            - Path=/vehicle-service/**
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - name: Path
                  args:
                    pattern: /user-service/**


            - id: vehicle-service
              uri: lb://VEHICLE-SERVICE
              predicates:
                - name: Path
                  args:
                    pattern: /vehicle-service/**

            - id: parking-space-service
              uri: lb://PARKING-SPACE-SERVICE
              predicates:
                - name: Path
                  args:
                    pattern: /parking-space-service/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - name: Path
                  args:
                    pattern: /payment-service/**

            - id: security-service
              uri: lb://SECURITY-SERVICE
              predicates:
                - name: Path
                  args:
                      pattern: /security-service/**