server:
  port: 8090

spring:
  application:
    name: security-service
  config:
    import: "optional:configserver:http://localhost:8888"

  security:
    user:
      name: disabled
      password: disabled
